### PR TITLE
Move tokens to Theme

### PR DESCRIPTION
**Pull request by astrit**
This PR moves tokens from individual components to the Theme component. 
It is intended to be merged and used first on the #1507 PR

Also should we move other things to Theme for example fonts ?
 
This change affects the following components: 

1. Button
2. Calendar
3. Divider
4. Spacer
5. Text
6. Datepicker
7. Dropdown
8. Card
9. Container
10. Flex
11. Grid
12. IMG
13. Video
14. Menu Button
15. Segmented Control 
16. Primitive Listbox 
17. Primitive Ripple

Let me know if you see a problem with this change or if there should be done more checks.

### CODE REVIEW

**Comment by splashdust** [comment]
Not entirely sure about this one. If I understand correctly, it would require you to always use `<gds-theme>`? Let's discuss this tomorrow!

**Comment by astrit** [comment]
> Not entirely sure about this one. If I understand correctly, it would require you to always use `<gds-theme>`? Let's discuss this tomorrow!

That was the thinking behind it to wrap everything and once you do to provide tokens and common things through the theme. 

To give a little bit of context conversation was initiated here: 
https://github.com/seb-oss/green/pull/1507#discussion_r1719525006

But yes I agree let's discuss it tomorrow!

**Comment by vsjolander** [comment]
Yea it's my thought that sparked this. I my thought was that `<gds-theme>` should handle all tokens and it helps with implementing darkmode, but I might have gotten this completely wrong.

Lets talk it over tomorrow 👍

**Comment by astrit** [comment]
Closing this PR due to the decision made with @splashdust and @vsjolander to consider a better approach in the future.

**Pull request closed without merging**
